const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const crypto=require('node:crypto');
test('bridge requires Google origin, unpredictable channel and exact response source',async()=>{
  const listeners=[];
  let frame,frames=0;
  const sent=[];
  const window={addEventListener:(_name,fn)=>listeners.push(fn),removeEventListener:(_name,fn)=>{const i=listeners.indexOf(fn);if(i>=0)listeners.splice(i,1);}};
  const context={window,URL,crypto,setTimeout,clearTimeout,document:{createElement:()=>({remove(){}}),body:{appendChild:item=>{frame=item;frames++;}}}};
  vm.runInNewContext(fs.readFileSync('js/google-bridge.js','utf8'),context);
  const emit=event=>listeners.slice().forEach(fn=>fn(event));
  const pending=window.LoanBridge.request('https://script.google.com/macros/s/backend/exec',{action:'list',pass:'test-only'});
  const channel=new URL(frame.src).searchParams.get('channel');
  assert.ok(channel.length>=20);
  assert.ok(!frame.src.includes('test-only'));
  const peer={postMessage:(message,origin)=>sent.push({message,origin})};
  const ready={marker:'loan-tracker-bridge',channel,kind:'ready'};
  emit({origin:'https://evil.test',source:peer,data:ready});
  emit({origin:'https://script.googleusercontent.com',source:peer,data:{...ready,channel:'wrong'}});
  await Promise.resolve();
  assert.equal(sent.length,0);
  const origin='https://n-test-0lu-script.googleusercontent.com';
  emit({origin,source:peer,data:ready});
  await Promise.resolve(); await Promise.resolve();
  assert.equal(sent.length,1);
  assert.equal(sent[0].origin,origin);
  const reply={marker:'loan-tracker-bridge',channel,kind:'result',id:sent[0].message.id,result:{ok:true,payments:[]}};
  emit({origin,source:{},data:reply});
  emit({origin:'https://evil.test',source:peer,data:reply});
  emit({origin,source:peer,data:reply});
  assert.equal((await pending).ok,true);
  assert.equal(frames,1);
});
